export const VALUE_CHANGED = 'VALUE_CHANGED_AVALIATION';
export const RESET_FORM = 'RESET_FORM_AVALIATION';
export const GET_LIST = 'GET_LIST_AVALIATION';
export const GET_ITEM = 'GET_ITEM_AVALIATION';
export const DELETE_ITEM = 'DELETE_AVALIATION';

export const SUGGESTION = {
    VALUE_CHANGED_SUGESTION : 'VALUE_CHANGED_SUGESTION_AVALIATION',
    VALUE_CHANGED_ITEM_SUGESTION : 'VALUE_CHANGED_ITEM_SUGESTION_AVALIATION',
    VALUE_CHANGED_KEY_DOWN_SUGESTION : 'VALUE_CHANGED_KEY_DOWN_SUGESTION_AVALIATION',
    REMOVE_ITEM_SUGGESTION : 'REMOVE_ITEM_SUGGESTION_AVALIATION',
}
export const FORM_QUESTION = {
    VALUE_CHANGED_OPTION : 'VALUE_CHANGED_OPTION_AVALIATION',
    SAVE_QUESTION : 'SAVE_QUESTION',
    ADD_OPTION : 'ADD_OPTION_AVALIATION',
    REMOVE_OPTION : 'REMOVE_OPTION_AVALIATION',
}